{% set version = "0.2.1" %}

package:
  name: dxchange
  version: {{ version }}

source:
  url: https://github.com/data-exchange/dxchange/archive/v{{ version }}.tar.gz
  sha256: 3fa69c609adff4e9c599c8f0b46c4bbabf2980e68ae8ba11efa670d4187eeb3c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
  run:
    - python >={{ python_min }},<4
    - dxfile
    - edffile
    - h5py >=3.8
    - netcdf4
    - numpy >1.12,!=1.22.4
    - py-opencv
    - scipy >=1.0,<1.14
    - spefile
    - tifffile >=2019
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - dxchange
    - dxchange.reader
    - dxchange.writer
    - dxchange.exchange

about:
  home: http://dxchange.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Data I/O for tomography

extra:
  recipe-maintainers:
    - dgursoy
    - decarlof
    - ericdill
    - licode
    - ravescovi
    - tacaswell
