{% set version = "0.1.9" %}

package:
  name: dxchange
  version: {{ version }}

source:
  url: https://github.com/data-exchange/dxchange/archive/v{{ version }}.tar.gz
  sha256: c1ef77b27629578c618db9dcb64bcf12c6295fdae11f54d983a68b5ca6ae473c


build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python 3.6
    - setuptools >=45
  run:
    - python >=3.6,<4
    - dxfile
    - edffile
    - h5py >=3.8
    - netcdf4
    - numpy >1.12,!=1.22.4
    - python-opencv
    - scipy >=1.0,<1.14
    - spefile
    - tifffile >=2019
    - pandas

test:
  imports:
    - dxchange
    - dxchange.reader
    - dxchange.writer
    - dxchange.exchange

about:
  home: http://dxchange.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Data I/O for tomography

extra:
  recipe-maintainers:
    - dgursoy
    - decarlof
    - ericdill
    - licode
    - ravescovi
    - tacaswell
