{% set version = "0.2.0" %}

package:
  name: dxchange
  version: {{ version }}

source:
  url: https://github.com/data-exchange/dxchange/archive/v{{ version }}.tar.gz
  sha256: 98850c1c2292e93ba839c81d21a12b6291ecf3340b71da092de5692343bdd1c7


build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=45
  run:
    - python >={{ python_min }},<4
    - dxfile
    - edffile
    - h5py >=3.8
    - netcdf4
    - numpy >1.12,!=1.22.4
    - py-opencv
    - scipy >=1.0,<1.14
    - spefile
    - tifffile >=2019
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - dxchange
    - dxchange.reader
    - dxchange.writer
    - dxchange.exchange

about:
  home: http://dxchange.readthedocs.org
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Data I/O for tomography

extra:
  recipe-maintainers:
    - dgursoy
    - decarlof
    - ericdill
    - licode
    - ravescovi
    - tacaswell
